plugins {
    id "com.android.application"
}

android {
    namespace "com.aliverbiopharma.app"
    compileSdk 36

    defaultConfig {
        applicationId "com.aliverbiopharma.app"
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName "1.0.3"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".test"
            versionNameSuffix "-test"
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
