plugins {
    id "com.android.application"
}

android {
    namespace "com.aliverbiopharma.app"
    compileSdk 36

    defaultConfig {
        applicationId "com.aliverbiopharma.app"
        minSdk 23
        targetSdk 36
        versionCode 3
        versionName "1.0.2"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".test"
            versionNameSuffix "-test"
        }
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
            applicationIdSuffix ".install"
            versionNameSuffix "-install"
        }
    }
}
